root = "."
cmd = "go build -o tmp/cultivator ./cmd/api"
bin = "tmp/cultivator"
full_env = []
env_file = ".env"
ignore_dir = ["tmp", "vendor", "migrations"]
build_delay = 200
build_log = "tmp/air_build.log"
run_log = "tmp/air_run.log"
main_file = "cmd/api/main.go"
include_ext = ["go", "yaml", "sql"]

[log]
time = false

[color]
main = "magenta"
build = "yellow"
run = "green"
